In [11]:
from  keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
import numpy as np

In [5]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])


In [14]:
# integer encode the documents
vocab_size = 30
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[13, 26], [28, 16], [14, 10], [17, 16], [28], [11], [10, 10], [23, 28], [10, 16], [7, 4, 26, 26]]


In [12]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[21 24  0  0]
 [21  3  0  0]
 [ 6  2  0  0]
 [10  3  0  0]
 [16  0  0  0]
 [11  0  0  0]
 [ 8  2  0  0]
 [ 6 21  0  0]
 [ 8  3  0  0]
 [11  7 24  8]]
